apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-redis-master
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: master
        image: redis
        ports:
        - containerPort: 6379

---        

apiVersion: v1
kind: Service
metadata:
  name: cd-redis-service
  labels:
    app: cd-redis-service
    role: master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master