apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-server
spec: # referente ao Deployment
    replicas: 1
    selector: #selector utilizado para criar o service
        matchLabels:
            app: mysql-server
            tier: db
    template: # referente ao POD
        metadata:
            labels:
                app: mysql-server
                tier: db
        spec:
            containers:
            - image: mysql:5.7
              name: mysql-server
              args:
                - "--ignore-db-dir=lost+found"
              env:
              - name: MYSQL_ROOT_PASSWORD
                value: root
              ports:
              - containerPort: 3306
              volumeMounts: #monta os volumes definidos logo abaixo
              - name: mysql-persistent-storage
                mountPath: /var/lib/mysql
            
            volumes: # Definição do volume
            - name: mysql-persistent-storage
              persistentVolumeClaim:
                claimName: mysql-pv-claim
            