apiVersion: apps/v1
kind: Deployment
metadata:
  name: app

spec:
  selector:
    matchLabels:
      app: app

  template:
    metadata:
      labels:
        app: app
    
    spec:
      containers:
      - name: app
        image: img-app-deployment
        ports:
        - containerPort: 80

        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password

        envFrom:
        - configMapRef:
            name: cd-app-conf

        volumeMounts:
        - name: cd-app-conf
          mountPath: /var/www/.env
          subPath: .env

      volumes:
      - name: cd-app-conf
        configMap:
          name: cd-app-conf
          items:
            - key: env
              path: .env